import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { ClerkProvider } from '@clerk/nextjs';
import "./globals.css";

// 1. Import the new SidebarLayout shell
import SidebarLayout from "@/components/SidebarLayout"; 

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "PresentAI",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        {/* Added the font variables here so your custom fonts work perfectly! */}
        <body 
          className={`${geistSans.variable} ${geistMono.variable} min-h-full flex flex-col antialiased`} 
          suppressHydrationWarning
        >
          {/* 2. Wrap the entire app in the SidebarLayout */}
          <SidebarLayout>
            {children}
          </SidebarLayout>
        </body>
      </html>
    </ClerkProvider>
  );
}